### ISSUE TITLE
Support Git packages

### ISSUE THREAD

**Issue by sanmai-NL** [fredrikaverpil/creosote#115]
In `requirements.txt` and modern package managers in `pyproject.toml` alike: e.g.,`Pattern @ git+https://github.com/uob-vil/pattern.git`. 

When such a dependency is specified, it's incorrectly reported as unused by creosote 1.0.3.

**Comment by fredrikaverpil** [comment]
Thanks for reporting @sanmai-NL. Nice find.

**Comment by fredrikaverpil** [comment]
@sanmai-NL I'm thinking of how to support this. The repo name is not necessarily the same as the package name, so I don't think I can guess the package name only having the URI. I likely need to go to the URI and look or the package definition (e.g. the pyproject.toml, a setup.py or similar. 🤔

**Comment by fredrikaverpil** [comment]
Aha!
This could do the trick, very easily: https://github.com/package-url/packageurl-python

**Comment by fredrikaverpil** [comment]
Oh no, that ones does only use the URL as input and does not go out into the repo to try and figure out the package name...

**Comment by fredrikaverpil** [comment]
If you have the possibility, would you like to see if it works for you with these code changes?
https://github.com/fredrikaverpil/creosote/pull/117

**Comment by fredrikaverpil** [comment]
@sanmai-NL please see if v2.1.0 fixes this for you.

**Comment by sanmai-NL** [comment]
⛔️ Blocker: https://github.com/fredrikaverpil/creosote/issues/114#issuecomment-1455670134.

**Comment by fredrikaverpil** [comment]
I'm closing this for now. We can reopen this if needed.
