### ISSUE TITLE
False positives for extra_requires subdependencies, and for packages who's pypi name differs from import name

### ISSUE THREAD

**Issue by BrianPugh** [fredrikaverpil/creosote#123]
I just tried running creosote v2.2.0 on my project, [Belay](https://github.com/BrianPugh/belay):

```
creosote --venv .venv --paths belay --deps-file pyproject.toml --sections project.dependencies
```

The output:

```
Unused packages found: aiohttp, gitpython, typing-extensions
```

Without understanding creosote's internals, here's my speculations:

1. `aiohttp` is a [subdependency of fsspec[http]](https://github.com/fsspec/filesystem_spec/blob/fef43b296f40b23e67ee4519fa891bab04be39a9/setup.py#L53). Perhaps creosote doesn't handle `extra_requires` properly.
2. `gitpython` is used as `import git`; i.e. it's pypi package name and module name are different. [This stackoverflow answer ](https://stackoverflow.com/a/54853084) provides some idea of how one might draw the relation (note; it uses deprecated `pkg_resources`):

```
>>> import pkg_resources as pkg
>>> metadata_dir = pkg.get_distribution('gitpython').egg_info
>>> open('%s/%s' % (metadata_dir, 'top_level.txt')).read().rstrip()
"git"
```
3. `typing-extensions`, possibly same story as (2), it's used as `import typing_extensions`.

I imagine other popular python packages may run into issues, a few off the top of my head:

* `pillow` - `import PIL`
* `opencv-python` - `import cv2`

Unrelated side small feature request; allow the version to be printed out from the CLI via `creosote --version`. Thanks!

**Comment by fredrikaverpil** [comment]
Hi @BrianPugh and thanks for the report!

1. Hm, sub-dependencies not specified in the `pyproject.toml` could be a difficult case to solve nicely. I'll have to think about this one.
2. and 3. Creosote is actually covering for the case where the package name differs from the import naming, so I'm a bit surprised this did not work. I think a new argument `--verbose` could enable showing how the mapping is done for easier debugging on this, so I'll look into adding this first.

I'll have to look closer at this, maybe later today or next week.

> allow the version to be printed out from the CLI via creosote --version

👍 I had this planned, but didn't get around to do it yet. Also a bit bummed out about already having `-v`, oh well 😅

**Comment by and-semakin** [comment]
@fredrikaverpil I think it's better to use capital `-V` for version anyway. It seems to be some kind of a popular convention, at least `python` and `pip` work this way.

**Comment by fredrikaverpil** [comment]
I'm adding a `-V` and `--version` argument in https://github.com/fredrikaverpil/creosote/pull/126

**Comment by fredrikaverpil** [comment]
@BrianPugh I just increased debug logging using `--verbose` and I'll have a look at how creosote behaves in your repo in a bit.

**Comment by fredrikaverpil** [comment]
@BrianPugh I can reproduce this on my end. I'm pretty sure this error stems from that the glob is not case sensitive in https://github.com/fredrikaverpil/creosote/blob/main/src/creosote/resolvers.py#L39

**Comment by fredrikaverpil** [comment]
@BrianPugh if you update to v2.3.2 you should not see the false positive with `gitpython`.

About `aiohttp`, how come you don't specify your `fsspec` dependency like this instead?

```toml
[tool.poetry.dependencies]
fsspec = {version = "^2022.11.0", extras = ["http"]}
```

When I do this, creosote does no longer report `aiohttp` as being an unused dependency.

I'm looking into `typing_extensions` as it did not seem to be the same story as with `gitpython` 😅

**Comment by BrianPugh** [comment]
for `aiohttp`, I think you are absolutely correct, so that issue is on my side. Thanks for fixing gitpython! As of `v2.3.3` I no longer get any false positives! Marking this as closed for now.

**Comment by fredrikaverpil** [comment]
I'm glad you're no longer seeing any false positives!
Also, thank you so much for your patience, the project is kind of young and it exploded a bit today 😅 so a few more bugs to squash, I'm sure, before it'll calm down.
