### ISSUE TITLE
Issue running creosote in a large workspace

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/creosote#128]
Picking up on the discussion here https://github.com/fredrikaverpil/creosote/issues/114#issuecomment-1455851571 in this issue.

ping @sanmai-NL

**Comment by fredrikaverpil** [comment]
Hi again @sanmai-NL so I've released creosote 2.3.0 and where you can use the `--verbose` argument to get more output. Would you mind doing that and send me the log?

First, maybe we can try with just the `core` folder, in case we can figure out what you are seeing false positives there?

**Comment by fredrikaverpil** [comment]
I've fixed a globbing issue in #129 that may or may not be related to some of the issues you are seeing. So if you can, please supply a verbose log using this in-development version of creosote:

```bash
pipx install --suffix=@129 --force git+https://github.com/fredrikaverpil/creosote.git@refs/pull/129/head

creosote@129 -v .venv ... --verbose

pipx uninstall creosote@129
```

**Comment by fredrikaverpil** [comment]
@sanmai-NL quite a few fixes has been done today, so please try using the latest version (v2.3.3) and provide the full log output of creosote (`--verbose`) if you are still experiencing issues.

**Comment by sanmai-NL** [comment]
Thanks. How can I make sure that `--paths`.

I did the following.

`.pyproject.toml`:

```toml
[tool.pdm.dev-dependencies]
dev = [
    "creosote @ git+https://github.com/fredrikaverpil/creosote.git#main",
]
```

```sh
creosote --venv .venv --verbose --paths azure core datapipeline_ff
```

That works for me. Can you please document that consecutive `--paths` parameters override the previous? 

Single `--paths`: dependency references are found at least once in the union of the source code under the specified paths. Multiple `--paths`: dependency references are at least once in the source code under each path.

**Comment by fredrikaverpil** [comment]
> Thanks. How can I make sure that --paths.

I'm not sure if there was a question in there...? 😄 

> That works for me.

Do you mean you can finally scan your workspace/project? 🤞😅
Btw, I'm about to release a new version where I fix #145

> Can you please document that consecutive --paths parameters override the previous?

Sure. I'll just take your copy and use that. Thanks!

**Comment by fredrikaverpil** [comment]
> Can you please document that consecutive --paths parameters override the previous?

Hm, this was actually not my intent. I wanted to check for the dependencies you have specified in your pyproject.toml files, and then over a set of files or folders.

I'll look into this, but it seems like a separate bug. 😢

**Comment by fredrikaverpil** [comment]
@sanmai-NL I understand that you made creosote work in your large workspace and I’m therefore closing this issue. We can reopen this if misinterpreted you.
