### ISSUE TITLE
An --ignores argument?

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/creosote#130]
It's possible there is a use case for an `--ignore-packages` argument. The user can ignore certain packages and creosote would simply ignore reporting them as unused. The ignores already exists internally [here](https://github.com/fredrikaverpil/creosote/blob/fe37d360061a707613b5d50969e69e23dd468c11/src/creosote/parsers.py#L103-L104) so all that is needed to enable this is to pass an argument to the CLI and pass it onto that function.

The use case could be e.g. using SQLAlchemy with a database driver. You wouldn't import the database driver in your own source code. Instead you would tell SQLAlchemy to use it via e.g. connection or engine creation string. This would be too tricky to support for Creosote, I think.

To avoid forgetting about the ignores (if e.g. discontinuing the use of said database driver above), Creosote could complain if an ignored package is no longer found in the dependency file (pyproject.toml, requirements.txt, ...), prompting the user to also remove the ignore.

🤔 Would it also be useful to ignore certain files/folders from the source code scan?
Anyhow, this would in that case be a different CLI argument, like `--ignore-paths`.

I'm just leaving this thought here for now to simmer. Please upvote if you think this would be a good addition to Creosote. 😄

**Comment by fredrikaverpil** [comment]
Would it also be useful to ignore certain files/folders from the source code scan?

**Comment by fredrikaverpil** [comment]
It's actually even possible there is a need for ignoring venvs, if creosote ends up supporting multiple venvs. Use case example: `pip install --user`.

**Comment by fredrikaverpil** [comment]
It seems what we need here is an `--ignore-packages` argument but maybe also a good time to introduce the option to configure via `pyproject.toml` itself? 🤔

Maybe add add a `[tool.creosote]` section where all config can be stored...?

**Comment by grofte** [comment]
Isn't it more of an `--additional-packages`? And yes. definitely a good idea to off-load it into a configuration file.

**Comment by fredrikaverpil** [comment]
@grofte haha, yeah - much better 😄 

I would be super happy if anyone in need of this feature would like to give this a try:

```bash
$ pipx install --suffix=@130 --force git+https://github.com/fredrikaverpil/creosote.git@extend-with-packages
$ creosote@main ... --extend-with-packages <PKG1>..<PKG2>
$ pipx uninstall creosote@130
```
