### ISSUE TITLE
Dependencies of packages flagged as unused

### ISSUE THREAD

**Issue by joszko** [fredrikaverpil/creosote#132]
Hi,

My requirements.txt contains packages installed as dependencies of other modules (ex. Pandas requires pytz, pdfplumber requires Pillow and loguru requires colorama) that are not used as imports in code. They are flagged as unused. 

Can this be changed? The requirements are often available in METADATA file in dist-info folders.

**Comment by fredrikaverpil** [comment]
Hi @joszko would you please try it again with the latest release (v2.3.3). If you still experience issues, please provide the full log output when running creosote with the `--verbose` flag.

**Comment by fredrikaverpil** [comment]
@joszko I believe this will be fixed by #142 which is cooking.

Please reopen if you don't think this is correct.
