### ISSUE TITLE
Default --venv to $VIRTUAL_ENV

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/creosote#138]
### What feature request would you like to suggest?

Idea: instead of requiring the `--venv .venv`, it could simply pick up the value of `$VIRTUAL_ENV`. If this environment variable is not set, Creosote will exit and prompt the user to provide the `--venv` argument.

🤔 also, should perhaps `--venv` be deprecated in favor for `--venvs`. The use case could be that `-p .` is used or that user employs `pip install --user ...` (like [here](https://github.com/fredrikaverpil/creosote/issues/125#issuecomment-1464862589)). No, probably not. Seems like a weird use case.

### Will the feature request break backwards compatibility?

Yep.

**Comment by fredrikaverpil** [comment]
🤔 also, should perhaps `--venv` be deprecated in favor for `--venvs`. The use case could be that `-p .` is used or that user employs `pip install --user ...`.

**Comment by sanmai-NL** [comment]
Will this keep working when no virtual environment is used? Rather than exiting upon no valid `VIRTUAL_ENV` env var, log a warning?

**Comment by fredrikaverpil** [comment]
Sorry, I see now this got closed "as conpleted" by mistake. I just closed it as I'm not doing this. At least not anytime soon.
