### ISSUE TITLE
Creosote does not exit with expected status when unused deps are found

### ISSUE THREAD

**Issue by sanmai-NL** [fredrikaverpil/creosote#145]
### What happened?

It is customary for tools like Creosote to exit with a failure-signalling exit status (value other than zero) when an issue is found. Creosote doesn't. The effect is that CI/CD pipelines in principle cannot detect unused dependencies with Creosote.

### Reproduction steps

```fish
$ creosote --paths azure/ core/ datapipeline_ff/
Found packages in pyproject.toml: nsone, pip, pulumi, pulumi-azure-native, pulumi-command, pulumi-kubernetes, pulumi-ns1, setuptools
Oh no, bloated venv! 🤢 🪣
Unused packages found: nsone, pip, setuptools
$ echo $status
0
```

### Relevant log output

```shell
2.3.7 (current main branch revision)
```

**Comment by fredrikaverpil** [comment]
This sounds really strange. I'll have a look later today.

**Comment by fredrikaverpil** [comment]
Thanks for reporting @sanmai-NL 👍 
This was a pretty bad one.
