### ISSUE TITLE
Issue running on project that is based on Poetry and pyenv

### ISSUE THREAD

**Issue by matroscoe** [fredrikaverpil/creosote#159]
### What happened?

I was expecting it to just work and it was complaining about not being able to find `Could not find toml section project.dependencies.`

### Reproduction steps

1. `pip install creosote`
2. `creosote` (from inside the git folder as well as with the pyenv virtualenv active)

### Relevant log output

```shell
❯_: creosote
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.11.1/envs/<venv>/lib/python3.11/site-packages/creosote/parsers.py", line 44, in pyproject
    section_contents = dotty_contents[section]
                       ~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.1/envs/<venv>/lib/python3.11/site-packages/dotty_dict/dotty_dict.py", line 162, in __getitem__
    return get_from(self._split(item), self._data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.1/envs/<venv>/lib/python3.11/site-packages/dotty_dict/dotty_dict.py", line 154, in get_from
    data = data[it]
           ~~~~^^^^
KeyError: 'project'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/<venv>/bin/creosote", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.1/envs/<venv>/lib/python3.11/site-packages/creosote/cli.py", line 100, in main
    deps_reader.read(args.deps_file, args.sections)
  File "/home/ubuntu/.pyenv/versions/3.11.1/envs/<venv>/lib/python3.11/site-packages/creosote/parsers.py", line 124, in read
    self.pyproject(deps_file, sections)
  File "/home/ubuntu/.pyenv/versions/3.11.1/envs/<venv>/lib/python3.11/site-packages/creosote/parsers.py", line 46, in pyproject
    raise KeyError(f"Could not find toml section {section}.") from err
KeyError: 'Could not find toml section project.dependencies.'
```

**Comment by fredrikaverpil** [comment]
If you are using poetry you need to define the toml section which contains your dependencies.

Try this:

```bash
creosote --sections tool.poetry.dependencies
```

Creosote does not default to poetry. It defaults to PEP-621, which would mean `--sections project.dependencies`.

**Comment by matroscoe** [comment]
thanks, I get past that issue now but I am running into the following: 

``` shell
> creosote --sections tool.poetry.dependencies --venv ~/.pyenv/versions/venv>
Found packages in pyproject.toml: <internal-lib1>, <internal-lib2>, h5py, loguru, numpy, pint, pydantic
Oh no, bloated venv! 🤢 🪣
Unused packages found: <internal-lib1>, <internal-lib2>, h5py, loguru, numpy, pint, pydantic
```

all of those libraries have active imports in the library that is being used

**Comment by fredrikaverpil** [comment]
Have you specified the `--paths` or does your source code live in a "src" folder (the default)?

Please see the README.md for how to configure creosote and see the FAQ.

Also, please provide a full log output using `--verbose` if you still have issues.

**Comment by matroscoe** [comment]
sorry I didn't follow it I am not sure if it was my confusion, I will open a PR with an updated example for use with poetry and pyenv :) 

One last question, it now runs properly and I am getting this: 

```shell
❯_: creosote --sections tool.poetry.dependencies --venv ~/.pyenv/versions/<venv> --paths ./<root-namespace>
Found packages in pyproject.toml: <internal-lib-1>, <internal-lib-2>, h5py, loguru, numpy, pint, pydantic
Oh no, bloated venv! 🤢 🪣
Unused packages found: <internal-lib-1>, <internal-lib-2>
```

When i do a search through `*.py` files I can find imports for both `<internal-lib-1>, <internal-lib-2>` is there anything specific I need to do to have it work with internal libs?

**Comment by fredrikaverpil** [comment]
I don't know what you mean by "internal libs". Please provide a full log where you provide `--verbose` or it is very hard for me to understand your use case.

I don't think you need to open a PR. The docs are quite clear on what required arguments there are.

**Comment by fredrikaverpil** [comment]
@matroscoe how are these internal libs installed in your virtual environment?
Do they install a `internallib.dist-info/top_level.txt` file in your virtual environment's site-packages?
