### ISSUE TITLE
Automatically detect virtualenv

### ISSUE THREAD

**Issue by bendavis78** [fredrikaverpil/creosote#168]
### What feature request would you like to suggest?

It would be nice if creosote could simply detect the virtualenv it is installed in instead of having to pass it explicitly. A script can easily detect the current virtualenv by checking `sys.base_prefix`. If `sys.base_prefix` is different from `sys.prefix`, you're in a virtualenv. 

### Will the feature request break backwards compatibility?

I don't think this would break any backward compatibility. For example, you could:

1. Check for .venv (current default)
2. Check for sys.base_prefix
3. Give error if no virtualenv is found

**Comment by fredrikaverpil** [comment]
Hi @bendavis78 yeah this sounds doable.

I'm just wondering if the `sys` attributes are better than to look for `$VIRTUAL_ENV`, which I believe exists when you have activated a virtual environment.

**Comment by fredrikaverpil** [comment]
@bendavis78 I finally came around looking at this but I'm not sure I can implement this without potentially breaking the default behavior for some users.

Imagine the default value is `[".venv"]` and that you are running creosote with this, but having another virtual environment activated.

I can't see myself implementing this right now, but I could add this, feature flagged. This would mean you'd have to run creosote with a parameter anyways; e.g. `creosote --use-feature auto-detect-venv`. I guess this might defeat the purpose of not having to specify any arguments, or do you think it would be useful for you?
