### ISSUE TITLE
Doesn't seem to work with Pipenv

### ISSUE THREAD

**Issue by kovaacs** [fredrikaverpil/creosote#173]
### What happened?

`creosote --deps-file Pipfile --sections packages` causes `NotImplementedError: Dependency specs file Pipfile is not supported.`

I'm confused because the FAQ says Pipenv _is_ supported.

### Reproduction steps

1. Have a project that uses `Pipfile` to define dependencies
2. run `creosote --deps-file Pipfile --sections packages`

### Relevant log output

```shell
Creosote version: 2.6.2
Command: creosote --deps-file Pipfile --sections packages --verbose
Arguments: Namespace(verbose=True, format='default', paths=[], sections=['packages'], exclude_deps=[], deps_file='Pipfile', venvs=['.venv'], features=[])
Imports found in code:
Parsing Pipfile for dependencies...
```

**Comment by fredrikaverpil** [comment]
I believe I found the root cause. Would you mind giving this a try?

```bash
$ pipx install --suffix=@174 --force git+https://github.com/fredrikaverpil/creosote.git@refs/pull/174/head
$ creosote@174 --venv .venv ...
$ pipx uninstall creosote@174
```

The `174` refers to the PR I opened to fix this in #174.

I would like to do some slight refactoring to fix this properly along with adding a test, but I'll see if I can manage this weekend.

**Comment by kovaacs** [comment]
Unfortunately  I get the same error as before.
```
% creosote --deps-file Pipfile --sections packages
Traceback (most recent call last):
  File "[...]/bin/creosote", line 8, in <module>
    sys.exit(main())
  File "[...]/lib/python3.10/site-packages/creosote/cli.py", line 191, in main
    dependency_names = deps_reader.read()
  File "[...]/lib/python3.10/site-packages/creosote/parsers.py", line 48, in read
    raise NotImplementedError(
NotImplementedError: Dependency specs file Pipfile is not supported.

```

**Comment by fredrikaverpil** [comment]
@kovaacs can you show me how you define your dependencies in the your PIpfile?

**Comment by fredrikaverpil** [comment]
I'm using a Pipfile like this:

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.11"
```

...along with a venv and source folder that I created like so:

```bash
python -m venv .venv
source .venv/bin/activate
pip install requests

mkdir src
```

And when I run creosote from my local dev branch, I see this:

```bash
$ creosote --deps-file Pipfile --sections packages --paths src
Found dependencies in Pipfile: requests
Oh no, bloated venv! 🤢 🪣
Unused dependencies found: requests
```

**Comment by fredrikaverpil** [comment]
@kovaacs please try Creosote v2.6.3.

**Comment by kovaacs** [comment]
The new version no longer produces this error, but I still cannot get it to work. I'll see if I can fix it.

**Comment by fredrikaverpil** [comment]
@kovaacs let me know if you are still experiencing issues. When I tried it out, it worked on my machine™ 😄

**Comment by kovaacs** [comment]
Thanks, it works now. It just took me a bit of experimenting to dial in the correct combination of arguments.
