### ISSUE TITLE
Use the appropriate default values depending on the environment

### ISSUE THREAD

**Issue by kovaacs** [fredrikaverpil/creosote#176]
### What feature request would you like to suggest?

Upon running `creosote --deps-file Pipfile`, a `KeyError` is raised with the message `'Could not find toml section project.dependencies.'` Even though this information is documented in the readme, I suggest that the default value for sections should be changed to "packages" to align with Pipenv's default behavior. While I'm not well-versed in other environments, it seems logical to extend the same thought process to them. In essence, creosote should dynamically determine the appropriate default section based on the specified dependency file, ensuring a better user experience and consistency across different environments.

### Will the feature request break backwards compatibility?

I don't think so

**Comment by fredrikaverpil** [comment]
Hi @kovaacs 

> Upon running creosote --deps-file Pipfile, a KeyError is raised with the message 'Could not find toml section project.dependencies.' 

Yes, like you mention, this is expected, as this is the default value for that argument.

When the user is supplying a `pyproject.toml` file, Creosote won't know if you intend to use `project.dependencies` or e.g. `tool.poetry.dependencies` or something else. I could implement a mapper that would detect stuff from your dependencies spec file and cleverly decide whether to change the default value. But I'm not going to do that, to keep the code simple. It's simple enough for you to supply the toml section(s) you want Creosote to parse.

The Python ecosystem is far too fragmented to build convenience features like this into Creosote IMHO.
