### ISSUE TITLE
Test if pyproject.toml exists early, and/or find the appropriate alternatives

### ISSUE THREAD

**Issue by bramp** [fredrikaverpil/creosote#210]
### What feature request would you like to suggest?

Running `creosote` takes a few minutes on my machine, in part due to some large Google Cloud dependencies. Once it's finished parsing all the deps, I get the error: `Exception: File pyproject.toml does not exist`. This is easily fixed by adding `-d requirements.txt`, but I had to wait 3 minutes to see my mistake.

Can we do one of two things:

1) Upfront detect which dependency file is available, pyproject.toml or requirements[.txt|.in]

or

2) Check if those files exist early, so we can fail fast, instead of doing a lot of upfront work.

### Will the feature request break backwards compatibility?

The default sshould remain pyproject.toml, but if the user did not previously specify `-d` and they don't have `pyproject.toml` the new behaviour would potentially be a working run, whereas previously it would fail.  That is technically a breaking change, but one that seems acceptable

**Comment by fredrikaverpil** [comment]
Sounds you are running creosote on a pretty serious project there ❤️😄 

I think failing fast is the way to go. I whipped up something quick in #212 but which should work and can be extended to fail fast when other files/folders are not found. WDYT?

**Comment by fredrikaverpil** [comment]
```bash
❯ creosote -p . -d yolo.toml
2024-06-28 21:12:56.563 | ERROR    | creosote.config:fail_fast:197 - File not found: yolo.toml
```

**Comment by bramp** [comment]
Sadly, it's not that serious, but it seems adding a few of the Google SDKs just pulled in literally ~100 dependencies.

Thanks for implementing!
