### ISSUE TITLE
Support PEP 735 keys in `pyproject.toml`

### ISSUE THREAD

**Issue by sanmai-NL** [fredrikaverpil/creosote#221]
### What feature request would you like to suggest?

See https://peps.python.org/pep-0735/

### Will the feature request break backwards compatibility?

Some tools, [such as PDM v2.20.0 (2024-10-31)](https://github.com/pdm-project/pdm/blob/main/CHANGELOG.md#features--improvements-1), have migrated to this new standard, using a different key in `pyproject.toml` for dev dependencies.

**Comment by fredrikaverpil** [comment]
Thanks for the suggestion. I think I have it working but it would be great if you could help me verify it:

```bash
# Creosote build from PR #231
$ pipx install --suffix=@231 --force git+https://github.com/fredrikaverpil/creosote.git@refs/pull/231/head
$ creosote@231 -s dependency-groups
$ pipx uninstall creosote@231
```

**Comment by sanmai-NL** [comment]
Worked for me! Thanks.

**Comment by sanmai-NL** [comment]
@fredrikaverpil I didn't want to comment beyond the issue, but I have trouble taking up your request to test a PR locally. I don't use `pipx`,and tried using `uv`. Perhaps you can document how to test PR using various popular tools or at least, using bare bones `pip`. When I added the PR branch as PDM dependency rather than mutating my venv in-place, it raised an exception:
 
```text
[stderr] [RequirementError]: Invalid version for creosote @ git+https://github.com/fredrikaverpil/creosote.git@refs/pull/231/head: Invalid version: 'None'
```

Could you solve this (in future cases perhaps) on your side by providing working package metadata even for source packages in PR branches?

**Comment by fredrikaverpil** [comment]
Does this work for you?

```bash
pip install git+https://github.com/fredrikaverpil/creosote.git@refs/pull/231/head
```
